SELECT COUNT(*) FROM EMPLEADO_DOS

SELECT SEDE.NOMBRE AS SEDE, COUNT(*) AS EMPLEADOS FROM EMPLEADO_DOS 
JOIN SEDE ON EMPLEADO_DOS.SEDE = SEDE.NO
GROUP BY SEDE.NOMBRE

SELECT ESTRATO.NOMBRE AS ESTRATO, COUNT(*) AS EMPLEADOS FROM EMPLEADO_DOS 
JOIN ESTRATO ON EMPLEADO_DOS.ESTRATO = ESTRATO.NO
GROUP BY ESTRATO.NOMBRE

SELECT NOMBRES,FECHA_DE_CONTRATACION FROM EMPLEADO_DOS
WHERE FECHA_DE_CONTRATACION >= '01/02/14'
GROUP BY NOMBRES, FECHA_DE_CONTRATACION
ORDER BY FECHA_DE_CONTRATACION DESC

SELECT NOMBRES,FECHA_DE_CONTRATACION FROM EMPLEADO_DOS
GROUP BY NOMBRES, FECHA_DE_CONTRATACION
ORDER BY FECHA_DE_CONTRATACION DESC

SELECT NOMBRES,FECHA_DE_CONTRATACION FROM EMPLEADO_DOS
GROUP BY NOMBRES, FECHA_DE_CONTRATACION
ORDER BY FECHA_DE_CONTRATACION ASC

SELECT NOMBRES,FECHA_DE_CONTRATACION FROM EMPLEADO_DOS
WHERE FECHA_DE_CONTRATACION <= '01/02/91'
GROUP BY NOMBRES, FECHA_DE_CONTRATACION
ORDER BY FECHA_DE_CONTRATACION ASC

SELECT NOMBRES, SEDE.NOMBRE AS SEDE, CARGO.NOMBRE AS CARGO FROM EMPLEADO_DOS
JOIN CARGO ON EMPLEADO_DOS.CARGO = CARGO.NO
JOIN SEDE ON EMPLEADO_DOS.SEDE = SEDE.NO
WHERE EMPLEADO_DOS.DNI = 10662101

DELETE FROM EMPLEADO_DOS WHERE DNI = 10188530

SELECT DNI, FECHA_DE_CONTRATACION FROM EMPLEADO_DOS
WHERE FECHA_DE_CONTRATACION BETWEEN '1/1/2000' AND '1/1/2005'

SELECT NOMBRES, MAX(FECHA_DE_CONTRATACION), MIN(EDAD) FROM EMPLEADO_DOS
GROUP BY NOMBRES
ORDER BY NOMBRES DESC

SELECT NOMBRES, EDAD FROM EMPLEADO_DOS
WHERE EDAD BETWEEN 17 AND 25

SELECT AVG(EDAD) FROM EMPLEADO_DOS

SELECT SUM(SUELDO) FROM EMPLEADO_DOS

SELECT NOMBRES, SEDE.NOMBRE AS SEDE, ESTRATO.NOMBRE AS ESTRATO, FECHA_DE_CONTRATACION, SUELDO FROM EMPLEADO_DOS
JOIN SEDE ON SEDE.NO = EMPLEADO_DOS.SEDE
JOIN ESTRATO ON ESTRATO.NO = EMPLEADO_DOS.ESTRATO
WHERE SUELDO >= 3990019

SELECT NOMBRES, SEDE.NOMBRE AS SEDE, ESTRATO.NOMBRE AS ESTRATO, FECHA_DE_CONTRATACION, SUELDO FROM EMPLEADO_DOS
JOIN SEDE ON SEDE.NO = EMPLEADO_DOS.SEDE
JOIN ESTRATO ON ESTRATO.NO = EMPLEADO_DOS.ESTRATO
WHERE SUELDO >= 3990019
ORDER BY SUELDO DESC

SELECT NOMBRES, EDAD, CARGO.NOMBRE AS CARGO, SEDE.NOMBRE AS SEDE FROM EMPLEADO_DOS 
JOIN CARGO ON CARGO.NO = EMPLEADO_DOS.CARGO
JOIN SEDE ON SEDE.NO = EMPLEADO_DOS.SEDE
WHERE CARGO.NOMBRE = 'MEDICO' AND  SEDE.NOMBRE = 'SUR'
ORDER BY EDAD ASC

SELECT NOMBRES, EDAD, CARGO.NOMBRE AS CARGO, SEDE.NOMBRE AS SEDE FROM EMPLEADO_DOS 
JOIN CARGO ON CARGO.NO = EMPLEADO_DOS.CARGO
JOIN SEDE ON SEDE.NO = EMPLEADO_DOS.SEDE
WHERE CARGO.NOMBRE = 'MEDICO' AND  SEDE.NOMBRE = 'SUR' AND EDAD <= 21
ORDER BY EDAD ASC

SELECT ESTRATO.NOMBRE AS ESTRATO, COUNT(*) AS EMPLEADOS FROM EMPLEADO_DOS 
JOIN ESTRATO ON EMPLEADO_DOS.ESTRATO = ESTRATO.NO
GROUP BY ESTRATO.NOMBRE
ORDER BY ESTRATO.NOMBRE ASC

SELECT SEDE.NOMBRE AS SEDE, COUNT(*) AS EMPLEADOS FROM EMPLEADO_DOS 
JOIN SEDE ON EMPLEADO_DOS.SEDE = SEDE.NO
GROUP BY SEDE.NOMBRE


